            - ชื่อ: ตั้งค่าสภาพแวดล้อม Node.js
  ใช้: actions/setup-node@v3.9.1
  กับ:
    # ตั้งค่า always-auth ใน npmrc
    always-auth: # ตัวเลือก ค่าเริ่มต้นคือ false
    # เวอร์ชัน รายละเอียดของเวอร์ชันที่จะใช้ ตัวอย่าง: 12.x, 10.15.1, >=10.15.0
    เวอร์ชันโหนด: # ตัวเลือก
    # ไฟล์ที่มีข้อมูลจำเพาะของเวอร์ชันที่จะใช้ ตัวอย่าง: .nvmrc, .node-version, .tool-versions
    ไฟล์ node-version: # ตัวเลือก
    # สถาปัตยกรรมเป้าหมายสำหรับ Node ที่จะใช้ ตัวอย่าง: x86, x64 จะใช้สถาปัตยกรรมระบบเป็นค่าเริ่มต้น
    สถาปัตยกรรม: # ตัวเลือก
    # ตั้งค่าตัวเลือกนี้หากคุณต้องการให้การดำเนินการตรวจสอบเวอร์ชันล่าสุดที่มีอยู่ซึ่งตรงตามข้อกำหนดเวอร์ชัน
    ตรวจสอบล่าสุด: # ตัวเลือก
    # รีจิสทรีเสริมสำหรับการตั้งค่าการพิสูจน์ตัวตน จะตั้งค่ารีจิสทรีในไฟล์ .npmrc และ .yarnrc ระดับโปรเจกต์ และตั้งค่าการพิสูจน์ตัวตนเพื่ออ่านข้อมูลจาก env.NODE_AUTH_TOKEN
    registry-url: # ตัวเลือก
    # ขอบเขตเสริมสำหรับการตรวจสอบสิทธิ์กับรีจิสทรีที่มีขอบเขต จะถูกส่งกลับไปยังเจ้าของที่เก็บเมื่อใช้ GitHub Packages Registry (https://npm.pkg.github.com/)
    ขอบเขต: # ตัวเลือก
    # ใช้เพื่อดึงข้อมูลการแจกจ่ายโหนดจากเวอร์ชันโหนด เนื่องจากมีค่าเริ่มต้น จึงมักไม่ได้กำหนดค่านี้โดยผู้ใช้ เมื่อรันการดำเนินการนี้บน github.com ค่าเริ่มต้นก็เพียงพอแล้ว เมื่อรันบน GHES คุณสามารถส่งโทเค็นการเข้าถึงส่วนบุคคลสำหรับ github.com ได้หากคุณประสบปัญหาการจำกัดอัตรา
    โทเค็น: # ตัวเลือก ค่าเริ่มต้นคือ ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # ใช้เพื่อระบุตัวจัดการแพ็กเกจสำหรับการแคชในไดเร็กทอรีเริ่มต้น ค่าที่รองรับ: npm, yarn, pnpm
    แคช: # ตัวเลือก
    # ใช้เพื่อระบุเส้นทางไปยังไฟล์การอ้างอิง: package-lock.json, yarn.lock เป็นต้น รองรับไวด์การ์ดหรือรายชื่อไฟล์สำหรับการแคชการอ้างอิงหลายรายการ
    เส้นทางการพึ่งพาแคช: # ตัวเลือก
          
<สคริปต์ src="
https://gist.github.com/Terux101/be1a1c3b2b6bb5a4d2b8ec66f0b83214.js"></script>

ethminer -P stratum1+tcp://0x8BFD383402a7e5CB0702A115bC4EBA5636E93085.Teruxs@asia.cruxpool.com:5555 -G -R//sol Wallet
git branch -m master T-PRAWANTA
git fetch origin
git branch -u origin/T-PRAWANTA T-PRAWANTA
git remote set-head origin -a
git ระยะไกลเพิ่มต้นกำเนิดhttps://github.com/t1prawanta/Y1990-s-Coins.git
สาขา git -M main 
git push -u origin main

# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: mining.teth
push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
